[  global ]  

# 100 MB
max_body_size = 104857600 

[default_error_pages]
400 = "/errors/400.html"
403 = "/errors/403.html"
404 = "/errors/404.html"
500 = "/errors/500.html"
503 = "/errors/503.html"

[[servers]]
host = "0.0.0.0"
port = [8080, 8081, 8082]
hostnames = ["example.com", "www.example.com", "nabil.com"]

[[servers.routes]]
path = "/"
root = "/"  
index = ["index.html"]	
methods = ["GET", "POST", "DELETE"] 
autoindex = true

[[servers.routes]]
path = "/cgi-bin"
root = "/new-site"
index = ["form.html"]
methods = ["GET", "DELETE"]
extensions = [".py"]
interpreter = "/usr/bin/env"
autoindex = true

[[servers.routes]]
path = "/new-site"
root = "/"
methods = ["GET", "POST", "DELETE"]
extensions = [".php", ".py"]
interpreter = "/usr/bin/env"
autoindex = true

[[servers.routes]]
path = "/not-found"
root = "/"
methods = ["GET", "POST", "DELETE"]
autoindex = false

[[servers.routes]]
path = "/old-site"
redirect = "/"
methods = ["GET", "POST", "DELETE"]

[[servers]]
host = "127.0.0.1"
port = [8090, 8091, 8092]

hostnames = ["api.example.com", "beta.example.com"]

[[servers.routes]]
path = "/"
root = "/somewhere"
index = ["index.html"]
methods = ["GET", "POST", "DELETE"]

[[servers.routes]]
path = "/upload"
root = "/"
methods = ["GET", "POST"]
autoindex = true
