[  global ]  

max_body_size = 100000000000000000000
# 1048772
# 1048766
[default_error_pages]

400 = "/errors/400.html" # Bad Request
403 = "/errors/403.html" # Forbidden
404 = "/errors/404.html" # Not Found
500 = "/errors/500.html" # Internal Server Error
503 = "/errors/503.html" # Service Unavailable

[[servers]]
host = "0.0.0.0" # Listen on all available network interfaces
port = [10093] # Listen on port 8080
hostnames = ["example.com", "www.example.com"  ]

[[servers.routes]]
path = "/"
root = "/"  	# Base directory for files
index = ["index.html"]		# Requirement: "Set a default file  to serve when the request is for a directory"
methods = ["GET",  "POST"] 	# Requirement: "Define a list of accepted HTTP methods"
autoindex = true 			# Requirement: "Enable or disable directory listing"

[[servers.routes]]
path = "/cgi-bin"
root = "/var/www/cgi-bin"
methods = ["GET", "POST"]
extensions = [".php"]
interpreter = "/usr/bin/php-cgi"

[[servers.routes]]
path = "/new-site"
root = "/"
methods = ["GET", "POST"]
# index = ["file.html", "form.html"]
# redirect = "/old-site"
extensions = [".php", ".py"]
interpreter = "/usr/bin/env"
autoindex = true

[[servers.routes]]
path = "/request"
root = "/srcs"
methods = ["GET", "POST"]
index = ["index.html", "form.html", "HTTPRequest.cpp"]
extensions = [".php", ".py"]
interpreter = "/usr/bin/env"

[[servers.routes]]
path = "/old-site"
root = "/"
# redirect = "/"
methods = ["POST"]
index = ["index.html", "form.html"]
# methods = ["GET"]

# [[     servers]]
# host = "0.0.0.0"
# port = 8081

# hostnames = ["api.example.com", "beta.example.com"]

# [[         servers.routes    ]]
# path = "/"
# root = "/var/www/api"
# index = ["api.php"]
# methods = ["GET", "POST", "DELETE"]

# [[servers.routes]]
# path = "/cgi"
# root = "/var/www/cgi-bin"
# methods = ["GET", "POST"]
# extensions = [".php", ".py"]
# interpreter = "/usr/bin/php-cgi"